version: '3.7'
services:
  cron:
    image: fballiano/magento2-cron:M2.4
    depends_on:
      - apache
      - varnish
    links:
      - db
      - cache
      - sessions
      - clusterdata
      - apache
      - varnish
      - elasticsearch
    volumes:
      - type: bind
        source: ../betagento
        target: /var/www/html
        consistency: delegated
      - type: bind
        source: ./certs/varnish.secret
        target: /varnish.secret
        consistency: consistent
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  ssl:
    image: fballiano/nginx-ssl-for-magento2
    depends_on:
      - varnish
    links:
      - varnish
    ports:
      - "443:443"

  varnish:
    image: fballiano/varnish:M2.4
    ports:
      - "80:80"
      - "6082:6082"
    depends_on:
      - apache
    links:
      - apache
    volumes:
      - ./certs/varnish.vcl:/etc/varnish/default.vcl
      - ./certs/varnish.secret:/etc/varnish/secret
    environment:
      - CACHE_SIZE=256M

  apache:
    image: fballiano/magento2-apache-php:M2.4
    depends_on:
      - db
      - cache
      - clusterdata
    links:
      - db
      - cache
      - sessions
      - clusterdata
    volumes:
      - type: bind
        source: ../betagento
        target: /var/www/html
        consistency: delegated
      - ../betagento/auth.json:/root/.composer/auth.json
      # Enable the next line if you want to add a custom php.ini
      #- ./php.ini:/usr/local/etc/php/conf.d/999-customphp.ini

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./data/sql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  elasticsearch:
    image: elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9300:9300"
      - "9200:9200"

  cache:
    image: fballiano/redis-volatile:M2.4

  clusterdata:
    image: fballiano/redis-volatile:M2.4

  sessions:
    image: redis:5

